/** Minimal badge catalog for the universities API. Derived from scripts/merit-badges.ts (discontinued excluded). */
export interface BadgeCatalogEntry {
  slug: string;
  title: string;
  eagleRequired: boolean;
}

export const MERIT_BADGES: readonly BadgeCatalogEntry[] = [
  {
    slug: "american-business",
    title: "American Business",
    eagleRequired: false,
  },
  {
    slug: "american-cultures",
    title: "American Cultures",
    eagleRequired: false,
  },
  {
    slug: "american-heritage",
    title: "American Heritage",
    eagleRequired: false,
  },
  { slug: "american-labor", title: "American Labor", eagleRequired: false },
  { slug: "animal-science", title: "Animal Science", eagleRequired: false },
  { slug: "animation", title: "Animation", eagleRequired: false },
  { slug: "archaeology", title: "Archaeology", eagleRequired: false },
  { slug: "archery", title: "Archery", eagleRequired: false },
  { slug: "architecture", title: "Architecture", eagleRequired: false },
  { slug: "art", title: "Art", eagleRequired: false },
  {
    slug: "artificial-intelligence",
    title: "Artificial Intelligence",
    eagleRequired: false,
  },
  { slug: "astronomy", title: "Astronomy", eagleRequired: false },
  { slug: "athletics", title: "Athletics", eagleRequired: false },
  {
    slug: "automotive-maintenance",
    title: "Automotive Maintenance",
    eagleRequired: false,
  },
  { slug: "aviation", title: "Aviation", eagleRequired: false },
  { slug: "backpacking", title: "Backpacking", eagleRequired: false },
  { slug: "basketry", title: "Basketry", eagleRequired: false },
  { slug: "bird-study", title: "Bird Study", eagleRequired: false },
  { slug: "bugling", title: "Bugling", eagleRequired: false },
  { slug: "camping", title: "Camping", eagleRequired: true },
  { slug: "canoeing", title: "Canoeing", eagleRequired: false },
  { slug: "chemistry", title: "Chemistry", eagleRequired: false },
  { slug: "chess", title: "Chess", eagleRequired: false },
  {
    slug: "citizenship-in-the-community",
    title: "Citizenship in the Community",
    eagleRequired: true,
  },
  {
    slug: "citizenship-in-the-nation",
    title: "Citizenship in the Nation",
    eagleRequired: true,
  },
  {
    slug: "citizenship-in-the-world",
    title: "Citizenship in the World",
    eagleRequired: true,
  },
  { slug: "climbing", title: "Climbing", eagleRequired: false },
  { slug: "coin-collecting", title: "Coin Collecting", eagleRequired: false },
  { slug: "collections", title: "Collections", eagleRequired: false },
  { slug: "communication", title: "Communication", eagleRequired: true },
  {
    slug: "competitive-gaming",
    title: "Competitive Gaming",
    eagleRequired: false,
  },
  {
    slug: "composite-materials",
    title: "Composite Materials",
    eagleRequired: false,
  },
  { slug: "cooking", title: "Cooking", eagleRequired: true },
  { slug: "crime-prevention", title: "Crime Prevention", eagleRequired: false },
  { slug: "cybersecurity", title: "Cybersecurity", eagleRequired: false },
  { slug: "cycling", title: "Cycling", eagleRequired: true },
  { slug: "dentistry", title: "Dentistry", eagleRequired: false },
  {
    slug: "digital-technology",
    title: "Digital Technology",
    eagleRequired: false,
  },
  {
    slug: "disabilities-awareness",
    title: "Disabilities Awareness",
    eagleRequired: false,
  },
  { slug: "dog-care", title: "Dog Care", eagleRequired: false },
  { slug: "drafting", title: "Drafting", eagleRequired: false },
  { slug: "electricity", title: "Electricity", eagleRequired: false },
  { slug: "electronics", title: "Electronics", eagleRequired: false },
  {
    slug: "emergency-preparedness",
    title: "Emergency Preparedness",
    eagleRequired: true,
  },
  { slug: "energy", title: "Energy", eagleRequired: false },
  { slug: "engineering", title: "Engineering", eagleRequired: false },
  { slug: "entrepreneurship", title: "Entrepreneurship", eagleRequired: false },
  {
    slug: "environmental-science",
    title: "Environmental Science",
    eagleRequired: true,
  },
  { slug: "exploration", title: "Exploration", eagleRequired: false },
  { slug: "family-life", title: "Family Life", eagleRequired: true },
  { slug: "farm-mechanics", title: "Farm Mechanics", eagleRequired: false },
  { slug: "fingerprinting", title: "Fingerprinting", eagleRequired: false },
  { slug: "fire-safety", title: "Fire Safety", eagleRequired: false },
  { slug: "first-aid", title: "First Aid", eagleRequired: true },
  {
    slug: "fish-and-wildlife-management",
    title: "Fish and Wildlife Management",
    eagleRequired: false,
  },
  { slug: "fishing", title: "Fishing", eagleRequired: false },
  { slug: "fly-fishing", title: "Fly Fishing", eagleRequired: false },
  { slug: "forestry", title: "Forestry", eagleRequired: false },
  { slug: "game-design", title: "Game Design", eagleRequired: false },
  { slug: "gardening", title: "Gardening", eagleRequired: false },
  { slug: "genealogy", title: "Genealogy", eagleRequired: false },
  { slug: "geocaching", title: "Geocaching", eagleRequired: false },
  { slug: "geology", title: "Geology", eagleRequired: false },
  { slug: "golf", title: "Golf", eagleRequired: false },
  { slug: "graphic-arts", title: "Graphic Arts", eagleRequired: false },
  {
    slug: "health-care-professions",
    title: "Health Care Professions",
    eagleRequired: false,
  },
  { slug: "hiking", title: "Hiking", eagleRequired: true },
  { slug: "home-repairs", title: "Home Repairs", eagleRequired: false },
  { slug: "horsemanship", title: "Horsemanship", eagleRequired: false },
  { slug: "indian-lore", title: "Indian Lore", eagleRequired: false },
  { slug: "insect-study", title: "Insect Study", eagleRequired: false },
  { slug: "inventing", title: "Inventing", eagleRequired: false },
  { slug: "journalism", title: "Journalism", eagleRequired: false },
  { slug: "kayaking", title: "Kayaking", eagleRequired: false },
  {
    slug: "landscape-architecture",
    title: "Landscape Architecture",
    eagleRequired: false,
  },
  { slug: "law", title: "Law", eagleRequired: false },
  { slug: "leatherwork", title: "Leatherwork", eagleRequired: false },
  { slug: "lifesaving", title: "Lifesaving", eagleRequired: true },
  { slug: "mammal-study", title: "Mammal Study", eagleRequired: false },
  { slug: "metalwork", title: "Metalwork", eagleRequired: false },
  {
    slug: "mining-in-society",
    title: "Mining in Society",
    eagleRequired: false,
  },
  {
    slug: "model-design-and-building",
    title: "Model Design and Building",
    eagleRequired: false,
  },
  { slug: "motorboating", title: "Motorboating", eagleRequired: false },
  { slug: "moviemaking", title: "Moviemaking", eagleRequired: false },
  { slug: "multisport", title: "Multisport", eagleRequired: false },
  { slug: "music", title: "Music", eagleRequired: false },
  { slug: "nature", title: "Nature", eagleRequired: false },
  { slug: "nuclear-science", title: "Nuclear Science", eagleRequired: false },
  { slug: "oceanography", title: "Oceanography", eagleRequired: false },
  { slug: "orienteering", title: "Orienteering", eagleRequired: false },
  { slug: "painting", title: "Painting", eagleRequired: false },
  { slug: "personal-fitness", title: "Personal Fitness", eagleRequired: true },
  {
    slug: "personal-management",
    title: "Personal Management",
    eagleRequired: true,
  },
  { slug: "pets", title: "Pets", eagleRequired: false },
  { slug: "photography", title: "Photography", eagleRequired: false },
  { slug: "pioneering", title: "Pioneering", eagleRequired: false },
  { slug: "plant-science", title: "Plant Science", eagleRequired: false },
  { slug: "plumbing", title: "Plumbing", eagleRequired: false },
  { slug: "pottery", title: "Pottery", eagleRequired: false },
  { slug: "programming", title: "Programming", eagleRequired: false },
  { slug: "public-health", title: "Public Health", eagleRequired: false },
  { slug: "public-speaking", title: "Public Speaking", eagleRequired: false },
  { slug: "pulp-and-paper", title: "Pulp and Paper", eagleRequired: false },
  { slug: "radio", title: "Radio", eagleRequired: false },
  { slug: "railroading", title: "Railroading", eagleRequired: false },
  { slug: "reading", title: "Reading", eagleRequired: false },
  {
    slug: "reptile-and-amphibian-study",
    title: "Reptile and Amphibian Study",
    eagleRequired: false,
  },
  { slug: "rifle-shooting", title: "Rifle Shooting", eagleRequired: false },
  { slug: "robotics", title: "Robotics", eagleRequired: false },
  { slug: "rowing", title: "Rowing", eagleRequired: false },
  { slug: "safety", title: "Safety", eagleRequired: false },
  { slug: "salesmanship", title: "Salesmanship", eagleRequired: false },
  { slug: "scholarship", title: "Scholarship", eagleRequired: false },
  {
    slug: "scouting-heritage",
    title: "Scouting Heritage",
    eagleRequired: false,
  },
  { slug: "scuba-diving", title: "Scuba Diving", eagleRequired: false },
  { slug: "sculpture", title: "Sculpture", eagleRequired: false },
  {
    slug: "search-and-rescue",
    title: "Search and Rescue",
    eagleRequired: false,
  },
  { slug: "shotgun-shooting", title: "Shotgun Shooting", eagleRequired: false },
  {
    slug: "signs-signals-and-codes",
    title: "Signs, Signals, and Codes",
    eagleRequired: false,
  },
  { slug: "skating", title: "Skating", eagleRequired: false },
  {
    slug: "small-boat-sailing",
    title: "Small-Boat Sailing",
    eagleRequired: false,
  },
  { slug: "snow-sports", title: "Snow Sports", eagleRequired: false },
  {
    slug: "soil-and-water-conservation",
    title: "Soil and Water Conservation",
    eagleRequired: false,
  },
  {
    slug: "space-exploration",
    title: "Space Exploration",
    eagleRequired: false,
  },
  { slug: "sports", title: "Sports", eagleRequired: false },
  { slug: "stamp-collecting", title: "Stamp Collecting", eagleRequired: false },
  { slug: "surveying", title: "Surveying", eagleRequired: false },
  { slug: "sustainability", title: "Sustainability", eagleRequired: true },
  { slug: "swimming", title: "Swimming", eagleRequired: true },
  { slug: "textile", title: "Textile", eagleRequired: false },
  { slug: "theater", title: "Theater", eagleRequired: false },
  { slug: "traffic-safety", title: "Traffic Safety", eagleRequired: false },
  {
    slug: "truck-transportation",
    title: "Truck Transportation",
    eagleRequired: false,
  },
  {
    slug: "veterinary-medicine",
    title: "Veterinary Medicine",
    eagleRequired: false,
  },
  { slug: "water-sports", title: "Water Sports", eagleRequired: false },
  { slug: "weather", title: "Weather", eagleRequired: false },
  { slug: "welding", title: "Welding", eagleRequired: false },
  { slug: "whitewater", title: "Whitewater", eagleRequired: false },
  {
    slug: "wilderness-survival",
    title: "Wilderness Survival",
    eagleRequired: false,
  },
  {
    slug: "wildland-fire-management",
    title: "Wildland Fire Management",
    eagleRequired: false,
  },
  { slug: "wood-carving", title: "Wood Carving", eagleRequired: false },
  { slug: "woodwork", title: "Woodwork", eagleRequired: false },
];

const badgeBySlug = new Map(MERIT_BADGES.map(b => [b.slug, b]));

export function findBadge(slug: string): BadgeCatalogEntry | undefined {
  return badgeBySlug.get(slug);
}
