/**
 * Static list of all merit badges from Scouting America
 * Source: https://www.scouting.org/skills/merit-badges/all/
 * Last updated: 2024-12-24
 *
 * This static list eliminates the need to fetch the index page,
 * which was causing inconsistent results due to Scouting.org's
 * variable HTML responses.
 */

export interface MeritBadge {
  id: number;
  title: string;
  slug: string;
  url: string;
  eagle_required: boolean;
  category: string;
  eagle_group?: string;
  discontinued?: boolean;
  discontinued_date?: string;
}

export const MERIT_BADGES: MeritBadge[] = [
  {
    id: 1,
    title: "American Business",
    slug: "american-business",
    url: "https://www.scouting.org/merit-badges/american-business/",
    eagle_required: false,
    category: "Business and Industry",
  },
  {
    id: 2,
    title: "American Cultures",
    slug: "american-cultures",
    url: "https://www.scouting.org/merit-badges/american-cultures/",
    eagle_required: false,
    category: "Personal Development",
  },
  {
    id: 3,
    title: "American Heritage",
    slug: "american-heritage",
    url: "https://www.scouting.org/merit-badges/american-heritage/",
    eagle_required: false,
    category: "Personal Development",
  },
  {
    id: 4,
    title: "American Labor",
    slug: "american-labor",
    url: "https://www.scouting.org/merit-badges/american-labor/",
    eagle_required: false,
    category: "Trades",
  },
  {
    id: 5,
    title: "Animal Science",
    slug: "animal-science",
    url: "https://www.scouting.org/merit-badges/animal-science/",
    eagle_required: false,
    category: "Agribusiness",
  },
  {
    id: 6,
    title: "Animation",
    slug: "animation",
    url: "https://www.scouting.org/merit-badges/animation/",
    eagle_required: false,
    category: "Arts and Crafts",
  },
  {
    id: 7,
    title: "Archaeology",
    slug: "archaeology",
    url: "https://www.scouting.org/merit-badges/archaeology/",
    eagle_required: false,
    category: "Natural Science",
  },
  {
    id: 8,
    title: "Archery",
    slug: "archery",
    url: "https://www.scouting.org/merit-badges/archery/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 9,
    title: "Architecture",
    slug: "architecture",
    url: "https://www.scouting.org/merit-badges/architecture/",
    eagle_required: false,
    category: "Professions",
  },
  {
    id: 10,
    title: "Art",
    slug: "art",
    url: "https://www.scouting.org/merit-badges/art/",
    eagle_required: false,
    category: "Arts and Crafts",
  },
  {
    id: 11,
    title: "Artificial Intelligence",
    slug: "artificial-intelligence",
    url: "https://www.scouting.org/merit-badges/artificial-intelligence/",
    eagle_required: false,
    category: "Physical Science",
  },
  {
    id: 12,
    title: "Astronomy",
    slug: "astronomy",
    url: "https://www.scouting.org/merit-badges/astronomy/",
    eagle_required: false,
    category: "Natural Science",
  },
  {
    id: 13,
    title: "Athletics",
    slug: "athletics",
    url: "https://www.scouting.org/merit-badges/athletics/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 14,
    title: "Automotive Maintenance",
    slug: "automotive-maintenance",
    url: "https://www.scouting.org/merit-badges/automotive-maintenance/",
    eagle_required: false,
    category: "Trades",
  },
  {
    id: 15,
    title: "Aviation",
    slug: "aviation",
    url: "https://www.scouting.org/merit-badges/aviation/",
    eagle_required: false,
    category: "Transportation",
  },
  {
    id: 16,
    title: "Backpacking",
    slug: "backpacking",
    url: "https://www.scouting.org/merit-badges/backpacking/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 17,
    title: "Basketry",
    slug: "basketry",
    url: "https://www.scouting.org/merit-badges/basketry/",
    eagle_required: false,
    category: "Arts and Crafts",
  },
  {
    id: 18,
    title: "Bird Study",
    slug: "bird-study",
    url: "https://www.scouting.org/merit-badges/bird-study/",
    eagle_required: false,
    category: "Natural Science",
  },
  {
    id: 19,
    title: "Bugling",
    slug: "bugling",
    url: "https://www.scouting.org/merit-badges/bugling/",
    eagle_required: false,
    category: "Arts and Crafts",
  },
  {
    id: 20,
    title: "Camping",
    slug: "camping",
    url: "https://www.scouting.org/merit-badges/camping/",
    eagle_required: true,
    category: "Hobbies",
  },
  {
    id: 21,
    title: "Canoeing",
    slug: "canoeing",
    url: "https://www.scouting.org/merit-badges/canoeing/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 22,
    title: "Chemistry",
    slug: "chemistry",
    url: "https://www.scouting.org/merit-badges/chemistry/",
    eagle_required: false,
    category: "Physical Science",
  },
  {
    id: 23,
    title: "Chess",
    slug: "chess",
    url: "https://www.scouting.org/merit-badges/chess/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 24,
    title: "Citizenship in Society",
    slug: "citizenship-in-society",
    url: "https://www.scouting.org/merit-badges/citizenship-in-society/",
    eagle_required: false,
    category: "Personal Development",
    discontinued: true,
    discontinued_date: "2026-02-27",
  },
  {
    id: 25,
    title: "Citizenship in the Community",
    slug: "citizenship-in-the-community",
    url: "https://www.scouting.org/merit-badges/citizenship-in-the-community/",
    eagle_required: true,
    category: "Personal Development",
  },
  {
    id: 26,
    title: "Citizenship in the Nation",
    slug: "citizenship-in-the-nation",
    url: "https://www.scouting.org/merit-badges/citizenship-in-the-nation/",
    eagle_required: true,
    category: "Personal Development",
  },
  {
    id: 27,
    title: "Citizenship in the World",
    slug: "citizenship-in-the-world",
    url: "https://www.scouting.org/merit-badges/citizenship-in-the-world/",
    eagle_required: true,
    category: "Personal Development",
  },
  {
    id: 28,
    title: "Climbing",
    slug: "climbing",
    url: "https://www.scouting.org/merit-badges/climbing/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 29,
    title: "Coin Collecting",
    slug: "coin-collecting",
    url: "https://www.scouting.org/merit-badges/coin-collecting/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 30,
    title: "Collections",
    slug: "collections",
    url: "https://www.scouting.org/merit-badges/collections/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 31,
    title: "Communication",
    slug: "communication",
    url: "https://www.scouting.org/merit-badges/communication/",
    eagle_required: true,
    category: "Personal Development",
  },
  {
    id: 159,
    title: "Competitive Gaming",
    slug: "competitive-gaming",
    url: "https://www.scouting.org/merit-badges/competitive-gaming/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 32,
    title: "Composite Materials",
    slug: "composite-materials",
    url: "https://www.scouting.org/merit-badges/composite-materials/",
    eagle_required: false,
    category: "Trades",
  },
  {
    id: 33,
    title: "Cooking",
    slug: "cooking",
    url: "https://www.scouting.org/merit-badges/cooking/",
    eagle_required: true,
    category: "Hobbies",
  },
  {
    id: 34,
    title: "Crime Prevention",
    slug: "crime-prevention",
    url: "https://www.scouting.org/merit-badges/crime-prevention/",
    eagle_required: false,
    category: "Public Service",
  },
  {
    id: 35,
    title: "Cybersecurity",
    slug: "cybersecurity",
    url: "https://www.scouting.org/merit-badges/cybersecurity/",
    eagle_required: false,
    category: "Physical Science",
  },
  {
    id: 36,
    title: "Cycling",
    slug: "cycling",
    url: "https://www.scouting.org/merit-badges/cycling/",
    eagle_required: true,
    category: "Sports",
    eagle_group: "fitness",
  },
  {
    id: 37,
    title: "Dentistry",
    slug: "dentistry",
    url: "https://www.scouting.org/merit-badges/dentistry/",
    eagle_required: false,
    category: "Professions",
  },
  {
    id: 38,
    title: "Digital Technology",
    slug: "digital-technology",
    url: "https://www.scouting.org/merit-badges/digital-technology/",
    eagle_required: false,
    category: "Physical Science",
  },
  {
    id: 39,
    title: "Disabilities Awareness",
    slug: "disabilities-awareness",
    url: "https://www.scouting.org/merit-badges/disabilities-awareness/",
    eagle_required: false,
    category: "Personal Development",
  },
  {
    id: 40,
    title: "Dog Care",
    slug: "dog-care",
    url: "https://www.scouting.org/merit-badges/dog-care/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 41,
    title: "Drafting",
    slug: "drafting",
    url: "https://www.scouting.org/merit-badges/drafting/",
    eagle_required: false,
    category: "Trades",
  },
  {
    id: 42,
    title: "Electricity",
    slug: "electricity",
    url: "https://www.scouting.org/merit-badges/electricity/",
    eagle_required: false,
    category: "Physical Science",
  },
  {
    id: 43,
    title: "Electronics",
    slug: "electronics",
    url: "https://www.scouting.org/merit-badges/electronics/",
    eagle_required: false,
    category: "Physical Science",
  },
  {
    id: 44,
    title: "Emergency Preparedness",
    slug: "emergency-preparedness",
    url: "https://www.scouting.org/merit-badges/emergency-preparedness/",
    eagle_required: true,
    category: "Public Service",
    eagle_group: "emergency",
  },
  {
    id: 45,
    title: "Energy",
    slug: "energy",
    url: "https://www.scouting.org/merit-badges/energy/",
    eagle_required: false,
    category: "Physical Science",
  },
  {
    id: 46,
    title: "Engineering",
    slug: "engineering",
    url: "https://www.scouting.org/merit-badges/engineering/",
    eagle_required: false,
    category: "Professions",
  },
  {
    id: 47,
    title: "Entrepreneurship",
    slug: "entrepreneurship",
    url: "https://www.scouting.org/merit-badges/entrepreneurship/",
    eagle_required: false,
    category: "Business and Industry",
  },
  {
    id: 48,
    title: "Environmental Science",
    slug: "environmental-science",
    url: "https://www.scouting.org/merit-badges/environmental-science/",
    eagle_required: true,
    category: "Conservation",
    eagle_group: "environment",
  },
  {
    id: 49,
    title: "Exploration",
    slug: "exploration",
    url: "https://www.scouting.org/merit-badges/exploration/",
    eagle_required: false,
    category: "Business and Industry",
  },
  {
    id: 50,
    title: "Family Life",
    slug: "family-life",
    url: "https://www.scouting.org/merit-badges/family-life/",
    eagle_required: true,
    category: "Personal Development",
  },
  {
    id: 51,
    title: "Farm Mechanics",
    slug: "farm-mechanics",
    url: "https://www.scouting.org/merit-badges/farm-mechanics/",
    eagle_required: false,
    category: "Agribusiness",
  },
  {
    id: 52,
    title: "Fingerprinting",
    slug: "fingerprinting",
    url: "https://www.scouting.org/merit-badges/fingerprinting/",
    eagle_required: false,
    category: "Public Service",
  },
  {
    id: 53,
    title: "Fire Safety",
    slug: "fire-safety",
    url: "https://www.scouting.org/merit-badges/fire-safety/",
    eagle_required: false,
    category: "Public Service",
  },
  {
    id: 54,
    title: "First Aid",
    slug: "first-aid",
    url: "https://www.scouting.org/merit-badges/first-aid/",
    eagle_required: true,
    category: "Public Service",
  },
  {
    id: 55,
    title: "Fish and Wildlife Management",
    slug: "fish-and-wildlife-management",
    url: "https://www.scouting.org/merit-badges/fish-wildlife-management/",
    eagle_required: false,
    category: "Conservation",
  },
  {
    id: 56,
    title: "Fishing",
    slug: "fishing",
    url: "https://www.scouting.org/merit-badges/fishing/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 57,
    title: "Fly Fishing",
    slug: "fly-fishing",
    url: "https://www.scouting.org/merit-badges/fly-fishing/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 58,
    title: "Forestry",
    slug: "forestry",
    url: "https://www.scouting.org/merit-badges/forestry/",
    eagle_required: false,
    category: "Conservation",
  },
  {
    id: 59,
    title: "Game Design",
    slug: "game-design",
    url: "https://www.scouting.org/merit-badges/game-design/",
    eagle_required: false,
    category: "Physical Science",
  },
  {
    id: 60,
    title: "Gardening",
    slug: "gardening",
    url: "https://www.scouting.org/merit-badges/gardening/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 61,
    title: "Genealogy",
    slug: "genealogy",
    url: "https://www.scouting.org/merit-badges/genealogy/",
    eagle_required: false,
    category: "Personal Development",
  },
  {
    id: 62,
    title: "Geocaching",
    slug: "geocaching",
    url: "https://www.scouting.org/merit-badges/geocaching/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 63,
    title: "Geology",
    slug: "geology",
    url: "https://www.scouting.org/merit-badges/geology/",
    eagle_required: false,
    category: "Natural Science",
  },
  {
    id: 64,
    title: "Golf",
    slug: "golf",
    url: "https://www.scouting.org/merit-badges/golf/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 65,
    title: "Graphic Arts",
    slug: "graphic-arts",
    url: "https://www.scouting.org/merit-badges/graphic-arts/",
    eagle_required: false,
    category: "Trades",
  },
  {
    id: 66,
    title: "Health Care Professions",
    slug: "health-care-professions",
    url: "https://www.scouting.org/merit-badges/health-care-professions/",
    eagle_required: false,
    category: "Professions",
  },
  {
    id: 67,
    title: "Hiking",
    slug: "hiking",
    url: "https://www.scouting.org/merit-badges/hiking/",
    eagle_required: true,
    category: "Hobbies",
    eagle_group: "fitness",
  },
  {
    id: 68,
    title: "Home Repairs",
    slug: "home-repairs",
    url: "https://www.scouting.org/merit-badges/home-repairs/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 69,
    title: "Horsemanship",
    slug: "horsemanship",
    url: "https://www.scouting.org/merit-badges/horsemanship/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 70,
    title: "Indian Lore",
    slug: "indian-lore",
    url: "https://www.scouting.org/merit-badges/indian-lore/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 71,
    title: "Insect Study",
    slug: "insect-study",
    url: "https://www.scouting.org/merit-badges/insect-study/",
    eagle_required: false,
    category: "Natural Science",
  },
  {
    id: 72,
    title: "Inventing",
    slug: "inventing",
    url: "https://www.scouting.org/merit-badges/inventing/",
    eagle_required: false,
    category: "Professions",
  },
  {
    id: 73,
    title: "Journalism",
    slug: "journalism",
    url: "https://www.scouting.org/merit-badges/journalism/",
    eagle_required: false,
    category: "Communications",
  },
  {
    id: 74,
    title: "Kayaking",
    slug: "kayaking",
    url: "https://www.scouting.org/merit-badges/kayaking/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 75,
    title: "Landscape Architecture",
    slug: "landscape-architecture",
    url: "https://www.scouting.org/merit-badges/landscape-architecture/",
    eagle_required: false,
    category: "Professions",
  },
  {
    id: 76,
    title: "Law",
    slug: "law",
    url: "https://www.scouting.org/merit-badges/law/",
    eagle_required: false,
    category: "Professions",
  },
  {
    id: 77,
    title: "Leatherwork",
    slug: "leatherwork",
    url: "https://www.scouting.org/merit-badges/leatherwork/",
    eagle_required: false,
    category: "Arts and Crafts",
  },
  {
    id: 78,
    title: "Lifesaving",
    slug: "lifesaving",
    url: "https://www.scouting.org/merit-badges/lifesaving/",
    eagle_required: true,
    category: "Public Service",
    eagle_group: "emergency",
  },
  {
    id: 79,
    title: "Mammal Study",
    slug: "mammal-study",
    url: "https://www.scouting.org/merit-badges/mammal-study/",
    eagle_required: false,
    category: "Natural Science",
  },
  {
    id: 80,
    title: "Metalwork",
    slug: "metalwork",
    url: "https://www.scouting.org/merit-badges/metalwork/",
    eagle_required: false,
    category: "Arts and Crafts",
  },
  {
    id: 81,
    title: "Mining in Society",
    slug: "mining-in-society",
    url: "https://www.scouting.org/merit-badges/mining-in-society/",
    eagle_required: false,
    category: "Natural Science",
  },
  {
    id: 82,
    title: "Model Design and Building",
    slug: "model-design-and-building",
    url: "https://www.scouting.org/merit-badges/model-design-and-building/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 83,
    title: "Motorboating",
    slug: "motorboating",
    url: "https://www.scouting.org/merit-badges/motorboating/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 84,
    title: "Moviemaking",
    slug: "moviemaking",
    url: "https://www.scouting.org/merit-badges/moviemaking/",
    eagle_required: false,
    category: "Communications",
  },
  {
    id: 85,
    title: "Multisport",
    slug: "multisport",
    url: "https://www.scouting.org/merit-badges/multisport/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 86,
    title: "Music",
    slug: "music",
    url: "https://www.scouting.org/merit-badges/music/",
    eagle_required: false,
    category: "Arts and Crafts",
  },
  {
    id: 87,
    title: "Nature",
    slug: "nature",
    url: "https://www.scouting.org/merit-badges/nature/",
    eagle_required: false,
    category: "Natural Science",
  },
  {
    id: 88,
    title: "Nuclear Science",
    slug: "nuclear-science",
    url: "https://www.scouting.org/merit-badges/nuclear-science/",
    eagle_required: false,
    category: "Physical Science",
  },
  {
    id: 89,
    title: "Oceanography",
    slug: "oceanography",
    url: "https://www.scouting.org/merit-badges/oceanography/",
    eagle_required: false,
    category: "Natural Science",
  },
  {
    id: 90,
    title: "Orienteering",
    slug: "orienteering",
    url: "https://www.scouting.org/merit-badges/orienteering/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 91,
    title: "Painting",
    slug: "painting",
    url: "https://www.scouting.org/merit-badges/painting/",
    eagle_required: false,
    category: "Trades",
  },
  {
    id: 92,
    title: "Personal Fitness",
    slug: "personal-fitness",
    url: "https://www.scouting.org/merit-badges/personal-fitness/",
    eagle_required: true,
    category: "Personal Development",
  },
  {
    id: 93,
    title: "Personal Management",
    slug: "personal-management",
    url: "https://www.scouting.org/merit-badges/personal-management/",
    eagle_required: true,
    category: "Personal Development",
  },
  {
    id: 94,
    title: "Pets",
    slug: "pets",
    url: "https://www.scouting.org/merit-badges/pets/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 95,
    title: "Photography",
    slug: "photography",
    url: "https://www.scouting.org/merit-badges/photography/",
    eagle_required: false,
    category: "Communications",
  },
  {
    id: 96,
    title: "Pioneering",
    slug: "pioneering",
    url: "https://www.scouting.org/merit-badges/pioneering/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 97,
    title: "Plant Science",
    slug: "plant-science",
    url: "https://www.scouting.org/merit-badges/plant-science/",
    eagle_required: false,
    category: "Agribusiness",
  },
  {
    id: 98,
    title: "Plumbing",
    slug: "plumbing",
    url: "https://www.scouting.org/merit-badges/plumbing/",
    eagle_required: false,
    category: "Trades",
  },
  {
    id: 99,
    title: "Pottery",
    slug: "pottery",
    url: "https://www.scouting.org/merit-badges/pottery/",
    eagle_required: false,
    category: "Arts and Crafts",
  },
  {
    id: 100,
    title: "Programming",
    slug: "programming",
    url: "https://www.scouting.org/merit-badges/programming/",
    eagle_required: false,
    category: "Physical Science",
  },
  {
    id: 101,
    title: "Public Health",
    slug: "public-health",
    url: "https://www.scouting.org/merit-badges/public-health/",
    eagle_required: false,
    category: "Public Service",
  },
  {
    id: 102,
    title: "Public Speaking",
    slug: "public-speaking",
    url: "https://www.scouting.org/merit-badges/public-speaking/",
    eagle_required: false,
    category: "Personal Development",
  },
  {
    id: 103,
    title: "Pulp and Paper",
    slug: "pulp-and-paper",
    url: "https://www.scouting.org/merit-badges/pulp-and-paper/",
    eagle_required: false,
    category: "Business and Industry",
  },
  {
    id: 104,
    title: "Radio",
    slug: "radio",
    url: "https://www.scouting.org/merit-badges/radio/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 105,
    title: "Railroading",
    slug: "railroading",
    url: "https://www.scouting.org/merit-badges/railroading/",
    eagle_required: false,
    category: "Transportation",
  },
  {
    id: 106,
    title: "Reading",
    slug: "reading",
    url: "https://www.scouting.org/merit-badges/reading/",
    eagle_required: false,
    category: "Personal Development",
  },
  {
    id: 107,
    title: "Reptile and Amphibian Study",
    slug: "reptile-and-amphibian-study",
    url: "https://www.scouting.org/merit-badges/reptile-and-amphibian-study/",
    eagle_required: false,
    category: "Natural Science",
  },
  {
    id: 108,
    title: "Rifle Shooting",
    slug: "rifle-shooting",
    url: "https://www.scouting.org/merit-badges/rifle-shooting/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 109,
    title: "Robotics",
    slug: "robotics",
    url: "https://www.scouting.org/merit-badges/robotics/",
    eagle_required: false,
    category: "Physical Science",
  },
  {
    id: 110,
    title: "Rowing",
    slug: "rowing",
    url: "https://www.scouting.org/merit-badges/rowing/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 111,
    title: "Safety",
    slug: "safety",
    url: "https://www.scouting.org/merit-badges/safety/",
    eagle_required: false,
    category: "Public Service",
  },
  {
    id: 112,
    title: "Salesmanship",
    slug: "salesmanship",
    url: "https://www.scouting.org/merit-badges/salesmanship/",
    eagle_required: false,
    category: "Business and Industry",
  },
  {
    id: 113,
    title: "Scholarship",
    slug: "scholarship",
    url: "https://www.scouting.org/merit-badges/scholarship/",
    eagle_required: false,
    category: "Personal Development",
  },
  {
    id: 114,
    title: "Scouting Heritage",
    slug: "scouting-heritage",
    url: "https://www.scouting.org/merit-badges/scouting-heritage/",
    eagle_required: false,
    category: "Personal Development",
  },
  {
    id: 115,
    title: "Scuba Diving",
    slug: "scuba-diving",
    url: "https://www.scouting.org/merit-badges/scuba-diving/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 116,
    title: "Sculpture",
    slug: "sculpture",
    url: "https://www.scouting.org/merit-badges/sculpture/",
    eagle_required: false,
    category: "Arts and Crafts",
  },
  {
    id: 117,
    title: "Search and Rescue",
    slug: "search-and-rescue",
    url: "https://www.scouting.org/merit-badges/search-and-rescue/",
    eagle_required: false,
    category: "Public Service",
  },
  {
    id: 118,
    title: "Shotgun Shooting",
    slug: "shotgun-shooting",
    url: "https://www.scouting.org/merit-badges/shotgun-shooting/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 119,
    title: "Signs, Signals, and Codes",
    slug: "signs-signals-and-codes",
    url: "https://www.scouting.org/merit-badges/signs-signals-and-codes/",
    eagle_required: false,
    category: "Communications",
  },
  {
    id: 120,
    title: "Skating",
    slug: "skating",
    url: "https://www.scouting.org/merit-badges/skating/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 121,
    title: "Small-Boat Sailing",
    slug: "small-boat-sailing",
    url: "https://www.scouting.org/merit-badges/small-boat-sailing/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 122,
    title: "Snow Sports",
    slug: "snow-sports",
    url: "https://www.scouting.org/merit-badges/snow-sports/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 123,
    title: "Soil and Water Conservation",
    slug: "soil-and-water-conservation",
    url: "https://www.scouting.org/merit-badges/soil-and-water-conservation/",
    eagle_required: false,
    category: "Conservation",
  },
  {
    id: 124,
    title: "Space Exploration",
    slug: "space-exploration",
    url: "https://www.scouting.org/merit-badges/space-exploration/",
    eagle_required: false,
    category: "Physical Science",
  },
  {
    id: 125,
    title: "Sports",
    slug: "sports",
    url: "https://www.scouting.org/merit-badges/sports/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 126,
    title: "Stamp Collecting",
    slug: "stamp-collecting",
    url: "https://www.scouting.org/merit-badges/stamp-collecting/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 127,
    title: "Surveying",
    slug: "surveying",
    url: "https://www.scouting.org/merit-badges/surveying/",
    eagle_required: false,
    category: "Professions",
  },
  {
    id: 128,
    title: "Sustainability",
    slug: "sustainability",
    url: "https://www.scouting.org/merit-badges/sustainability/",
    eagle_required: true,
    category: "Conservation",
    eagle_group: "environment",
  },
  {
    id: 129,
    title: "Swimming",
    slug: "swimming",
    url: "https://www.scouting.org/merit-badges/swimming/",
    eagle_required: true,
    category: "Sports",
    eagle_group: "fitness",
  },
  {
    id: 130,
    title: "Textile",
    slug: "textile",
    url: "https://www.scouting.org/merit-badges/textile/",
    eagle_required: false,
    category: "Business and Industry",
  },
  {
    id: 131,
    title: "Theater",
    slug: "theater",
    url: "https://www.scouting.org/merit-badges/theater/",
    eagle_required: false,
    category: "Arts and Crafts",
  },
  {
    id: 132,
    title: "Traffic Safety",
    slug: "traffic-safety",
    url: "https://www.scouting.org/merit-badges/traffic-safety/",
    eagle_required: false,
    category: "Personal Development",
  },
  {
    id: 133,
    title: "Truck Transportation",
    slug: "truck-transportation",
    url: "https://www.scouting.org/merit-badges/truck-transportation/",
    eagle_required: false,
    category: "Transportation",
  },
  {
    id: 134,
    title: "Veterinary Medicine",
    slug: "veterinary-medicine",
    url: "https://www.scouting.org/merit-badges/veterinary-medicine/",
    eagle_required: false,
    category: "Professions",
  },
  {
    id: 135,
    title: "Water Sports",
    slug: "water-sports",
    url: "https://www.scouting.org/merit-badges/water-sports/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 136,
    title: "Weather",
    slug: "weather",
    url: "https://www.scouting.org/merit-badges/weather/",
    eagle_required: false,
    category: "Natural Science",
  },
  {
    id: 137,
    title: "Welding",
    slug: "welding",
    url: "https://www.scouting.org/merit-badges/welding/",
    eagle_required: false,
    category: "Hobbies",
  },
  {
    id: 138,
    title: "Whitewater",
    slug: "whitewater",
    url: "https://www.scouting.org/merit-badges/whitewater/",
    eagle_required: false,
    category: "Sports",
  },
  {
    id: 139,
    title: "Wilderness Survival",
    slug: "wilderness-survival",
    url: "https://www.scouting.org/merit-badges/wilderness-survival/",
    eagle_required: false,
    category: "Personal Development",
  },
  {
    id: 160,
    title: "Wildland Fire Management",
    slug: "wildland-fire-management",
    url: "https://www.scouting.org/merit-badges/wildland-fire-management/",
    eagle_required: false,
    category: "Public Service",
  },
  {
    id: 140,
    title: "Wood Carving",
    slug: "wood-carving",
    url: "https://www.scouting.org/merit-badges/wood-carving/",
    eagle_required: false,
    category: "Arts and Crafts",
  },
  {
    id: 141,
    title: "Woodwork",
    slug: "woodwork",
    url: "https://www.scouting.org/merit-badges/woodwork/",
    eagle_required: false,
    category: "Professions",
  },
];

// Helper to find a badge by slug
export function findBadgeBySlug(slug: string): MeritBadge | undefined {
  return MERIT_BADGES.find(b => b.slug === slug);
}

// Get all eagle-required badges
export function getEagleRequiredBadges(): MeritBadge[] {
  return MERIT_BADGES.filter(b => b.eagle_required);
}

// Total count
export const TOTAL_BADGES = MERIT_BADGES.length;
export const EAGLE_REQUIRED_COUNT = MERIT_BADGES.filter(
  b => b.eagle_required,
).length;
